[alias]
astro-run-cov = "tarpaulin --all-features --timeout 120 -p astro-run --exclude-files crates/astro-runner/* --exclude-files crates/astro-run-test/* --exclude-files crates/astro-run-scheduler/* --skip-clean --out Xml"
