name: Test

on: [push, pull_request]
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: |
          export ASTRO_RUN_PROTOCOL_SKIP_BUILD=true
          cargo test --all --all-features -- --nocapture

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          export ASTRO_RUN_PROTOCOL_SKIP_BUILD=true

          cargo astro-run-cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
